[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest_report"
version = "0.0.1"
authors = [
  { name="PAUL BERNARD", email="Paul.Bernard@inria.fr" },
]
description = "A small tool to read a pytest XML report"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.scripts]
pytest_report = "cli:main"

[tool.ruff]

line-length = 300